### ISSUE TITLE
Attributions of licenses?

### ISSUE THREAD

**Issue by oztbizzle** [jaimehgb/RaiWebWallet#10]
Apologies if this is your own work, but the PoW stuff appears to have been sourced from elsewhere without attribution

**Comment by jaimehgb** [comment]
Hmm, it comes from here:
https://github.com/jaimehgb/RaiBlocksWebAssemblyPoW

:D

Maybe I should add something at the readme or something.

**Comment by oztbizzle** [comment]
Awesome sorry I just saw this massive bit of code pop up and was curious
