### ISSUE TITLE
If 2FA is prefilled (can happen on Chrome) then the 2FA box never is unhidden

### ISSUE THREAD

**Issue by oztbizzle** [jaimehgb/RaiWebWallet#11]
I can't fix this as the code isn't public. Essentially if the 2FA box has something in it from the last login which can occur for me with Chrome and LastPass then you have to manually edit the display:none on the 2fa box

**Comment by jaimehgb** [comment]
I guess it may work if the input is created and appended to the DOM instead of unhidding it when the 2fa code needs to be entered.

https://github.com/jaimehgb/RaiWebWallet/blob/master/js/custom.js#L943

**Comment by oztbizzle** [comment]
Perfecto!
