### ISSUE TITLE
Bounty wallet reset?

### ISSUE THREAD

**Issue by lalanza808** [jaimehgb/RaiWebWallet#19]
Hello,

I know recently due to some phishing all of the wallet identifiers were reset for users in the database. Did this also apply to the bounty wallet identifier? I was poking around and noticed that identifier wasn't valid anymore.

**Comment by jaimehgb** [comment]
Bounty wallet identifier?

**Comment by lalanza808** [comment]
The wallet mentioned in the bounty section of the readme: https://github.com/jaimehgb/RaiWebWallet#bounty

Per [this thread](https://www.reddit.com/r/RaiBlocks/comments/7mcjal/raiwalletcom_announcement_some_info_regarding/) all identifiers were reset. Does that include the wallet mentioned in the bug bounty?

**Comment by jaimehgb** [comment]
Oh true!
Try now, the old one should be valid again. Good luck! :D

**Comment by lalanza808** [comment]
Thanks!
