### ISSUE TITLE
many issues, but there's no import wallet function at least

### ISSUE THREAD

**Issue by dkliman** [jaimehgb/RaiWebWallet#2]
there's no 2fa.
no import wallet
lots missing but let's just start with those two?

what is this with unpocketed change? why would there be such a thing?

https://raiblocks.net/account/index.php?acc=xrb_1wq5wjcw9ijddzs4cj1je3k9aww7c8s8n5jwt76ddmnp4ddb7bm4t5urfd8r when i typed this my money is "not pocketed." maybe that will change?

**Comment by jaimehgb** [comment]
Hey!

2fa is a pending feature, to do when I find some free time :)
Same with import wallet. This one will come before the 2fa, I consider it more important. But it's not as easy as it may seem, when a wallet is imported it has to download all it's chain, encode it in the format it is stored in the wallet and then store it. But yeah, will come someday.

About the not pocketed issue. That's how raiblocks work. A transaction consists on 2 blocks: a send block made by the sender and a receive block made by the receiver. The funds are sent when the send block is broadcasted, that is not reversible. But those funds are not spendable by the receiver until he signs the receive block and adds it to his chain. Not pocketed means the receiver hasn't made those funds spendable for him, when he will do it is up to him. He can do it at any time and it's safe. The send tx cannot be cancelled at that point. Check raiblocks wiki, or the white paper. You'll find some more info there :)

Also, open one issue here at github for each issue you find, using a simple and straightforward title. This way updates and discussions can be organized better.

**Comment by dkliman** [comment]
ok well, I don't see any command to "pocket" my coins or to do anything like that... how do I actually perform that action? the status on the top says "running, block 313479 (3906613)"

**Comment by jaimehgb** [comment]
It is done automatically but your wallet needs to be synced. The number in brackets is the number of blocks downloaded but not yet processed.

I'm closing this issue as it's unrelated to raiwallet.com

**Comment by dkliman** [comment]
ok thanks for your help! looking forward to the 2fa and import wallet features
