### ISSUE TITLE
Asking for contact information of jaimehgb

### ISSUE THREAD

**Issue by Baumrinde2451** [jaimehgb/RaiWebWallet#21]
Hello,

i am not really experienced with github, i am sorry if the thread here is on the wrong place. 

i would like to contact jamiehgb, its about the railwallet bounty, i have one question to ask to continue with the work to get the passwort :D any help?

**Comment by jaimehgb** [comment]
You can contact me at the raiblocks discord chat. My nickname is jaimehgb too :D
Also, if it is not something sensitive it can be asked here
