### ISSUE TITLE
Update the code.

### ISSUE THREAD

**Issue by AugustoResende** [jaimehgb/RaiWebWallet#38]
The website code is running a new code, but i'ts not in this repo.

**Comment by jaimehgb** [comment]
True. I'm going to publish the latest version soon, along with the backend. 
What I don't know yet is if moving to a new repo or redoing this one entirely.

**Comment by pocesar** [comment]
@jaimehgb could you create an organization and split the codebase? the "pure" JS for the raiblocks inner functioning is really good. having to manually copy the file and place as a vendor on raiblocks projects is kind of a pain

**Comment by jaimehgb** [comment]
You have it here:
https://github.com/chriscohoat/rai-wallet
@pocesar
