### ISSUE TITLE
Wallet reported false balance after sending and receiving at the same time.

### ISSUE THREAD

**Issue by wonbinbk** [jaimehgb/RaiWebWallet#41]
So this morning I tried to send a small amount of XRB from one address to another address of mine, just to feel how quick the whole process is. 
My whole balance is A. After I sent B XRB from address 1 to address 2, the wallet reported I have A + B XRB which is not correct. After a refresh and re-login it reported correctly.

I think this is just a small thing (I don't want to say bug because it's unharm) but if you guys can fix this it would be better I guess.

**Comment by jaimehgb** [comment]
Fixed here: https://github.com/jaimehgb/RaiWalletV2/commit/b98c7c30529401a3e1f87450a444f1de99664ee2
